### ISSUE TITLE
black screen when push the viewcontroller into the navigation Stack

### ISSUE THREAD

**Issue by kareem5** [orangeloops/OLSDynamicHeaderViewController#2]
![simulator screen shot aug 27 2017 12 19 21 am](https://user-images.githubusercontent.com/8720772/29745216-6443202a-8abd-11e7-848e-5f4579d14406.png)
When I try to add the viewcontroller in the middle of the app, it's showing black screen. But it's working if I made the viewcontroller the initial ViewController.
Could you please help?

Thanks,

**Comment by clackmac** [comment]
Hey, thank you for the report.
This fix will be included in the next update.
