### ISSUE TITLE
How to create tableview frame I want do some customisation in bottom of the view

### ISSUE THREAD

**Issue by PodalakurPrasanth** [orangeloops/OLSDynamicHeaderViewController#3]
How to create tableview frame I want do some customisation in bottom of the view.. please help me . I am looking forward for your response

**Comment by clackmac** [comment]
Hey @PodalakurPrasanth, how are you?
Sorry, but I didn't quite understand what a re you trying to achieve ... could you please improve you explanation?

**Comment by clackmac** [comment]
Closing for now ...
Please, reopen if there's an issue we can help you with!
