### ISSUE TITLE
I need to integrate this library in a tabbar item, but when I tried to do this, it not work

### ISSUE THREAD

**Issue by Riickk18** [orangeloops/OLSDynamicHeaderViewController#4]
![IMG_20190916_112528](https://user-images.githubusercontent.com/39192381/64970905-ba9a6f80-d874-11e9-8c3e-132e73efb7a5.jpg)

If you can to help me.

**Comment by clackmac** [comment]
Hey, thank you for the report!!
Found the problem, fix will be released in the next update soon.
